# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20160727_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'Product categories', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='prodcut_categories',
        ),
    ]
